AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "test/dummy/**/*"
    - "vendor/**/*"
    - "bin/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Layout/LineLength:
  Max: 120
