AllCops:
  # This version matches the Ruby version in the development container (Dockerfile)
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "test/dummy/**/*"
    - "vendor/**/*"
    - "bin/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

# The Metrics/LineLength cop has been replaced by Layout/LineLength in RuboCop 0.78.0
Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
