version: "3"

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.compose
    volumes:
      - .:/workspaces/dynamic_links:cached
    depends_on:
      - citus
      - redis
    command: sleep infinity # Keep container running
    environment:
      CITUS_ENABLED: "true"
    user: vscode

  citus:
    image: citusdata/citus:13.0
    restart: unless-stopped
    volumes:
      - citus-data:/var/lib/postgresql/data
      - ./init-citus.sql:/docker-entrypoint-initdb.d/init-citus.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dynamic_links_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  citus-data:
  redis-data:
