version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.compose
    volumes:
      - .:/workspaces/dynamic_links:cached
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/dynamic_links_development
      REDIS_URL: redis://redis:6379/1
    command: sleep infinity  # Keep container running
    user: vscode

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dynamic_links_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data:
