source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in dynamic_links_analytics.gemspec.
gemspec

gem 'puma'

group :development do
  gem 'sqlite3'
end

group :development, :test do
  gem 'pg'
end
