services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: "20"
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    depends_on:
      - postgres
      - redis

    env_file:
      - ../.env
    environment:
      TZ: "${TZ:-Asia/Jakarta}"
      CLAUDE_CODE_VERSION: "latest"
      GIT_DELTA_VERSION: "0.18.2"
      ZSH_IN_DOCKER_VERSION: "1.2.0"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_POSTGRES_CPUS:-0}"
          memory: "${DOCKER_POSTGRES_MEMORY:-0}"
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-rails_dynamic_links_user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-hardcoded_password}"
      POSTGRES_DB: "${POSTGRES_DB:-rails_dynamic_links}"
    image: "postgres:17.5-bookworm"
    ports:
      - "${POSTGRES_PORT_FORWARD:-5432}:5432"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_REDIS_CPUS:-0}"
          memory: "${DOCKER_REDIS_MEMORY:-0}"
    image: "redis:8.0.3-bookworm"
    env_file:
      - ../.env
    ports:
      - "${REDIS_PORT_FORWARD:-6379}:6379"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    volumes:
      - "redis:/data"

  # oauth2-proxy:
  #   image: "quay.io/oauth2-proxy/oauth2-proxy:v7.6.0"
  #   env_file:
  #     - ../.env
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "${DOCKER_OAUTH2_PROXY_CPUS:-0}"
  #         memory: "${DOCKER_OAUTH2_PROXY_MEMORY:-0}"
  #   environment:
  #     OAUTH2_PROXY_PROVIDER: google
  #     OAUTH2_PROXY_CLIENT_ID: "${GOOGLE_CLIENT_ID:-}"
  #     OAUTH2_PROXY_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET:-}"
  #     OAUTH2_PROXY_COOKIE_SECRET: "${OAUTH2_PROXY_COOKIE_SECRET:-}"
  #     OAUTH2_PROXY_REDIRECT_URL: "${OAUTH2_PROXY_REDIRECT_URL:-http://localhost:4181/oauth2/callback}"
  #     OAUTH2_PROXY_UPSTREAMS: "${OAUTH2_PROXY_UPSTREAMS:-http://rails-app:3000}"
  #     OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  #     OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
  #     OAUTH2_PROXY_SET_XAUTHREQUEST: true
  #     OAUTH2_PROXY_PASS_ACCESS_TOKEN: true
  #     OAUTH2_PROXY_PASS_USER_HEADERS: true
  #     OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: true
  #     OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: false
  #   ports:
  #     - "${DOCKER_OAUTH2_PROXY_PORT_FORWARD:-127.0.0.1:4181}:4180"
  #   restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  #   stop_grace_period: "3s"

volumes:
  postgres:
  redis:
