default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: vscode
  password: vscode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dynamic_links_development

test:
  <<: *default
  database: dynamic_links_test
