default: &default
  adapter: "redis"
  url: "<%= ENV.fetch('REDIS_URL') { 'redis://redis:6379/1' } %>"

development:
  <<: *default
  channel_prefix: "rails_dynamic_links_development"

test:
  <<: *default
  adapter: "test"

production:
  <<: *default
  channel_prefix: "rails_dynamic_links_production"
