default: &default
  adapter: "postgresql"
  encoding: "unicode"
  database: "<%= ENV.fetch('POSTGRES_DB') { 'rails_dynamic_links' } %>"
  username: "<%= ENV.fetch('POSTGRES_USER') { 'rails_dynamic_links_user' } %>"
  password: "<%= ENV.fetch('POSTGRES_PASSWORD') { 'hardcoded_password' } %>"
  host: "<%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>"
  port: "<%= ENV.fetch('POSTGRES_PORT') { 5432 } %>"
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>"

development:
  primary:
    <<: *default
    database: "<%= ENV.fetch('POSTGRES_DB') { 'rails_dynamic_links' } %>_development"
  # Add additional databases here for multi-tenant support when needed
  # tenant_1:
  #   <<: *default
  #   database: "<%= ENV.fetch('POSTGRES_DB') { 'rails_dynamic_links' } %>_tenant_1_development"

test:
  primary:
    <<: *default
    database: "<%= ENV.fetch('POSTGRES_DB') { 'rails_dynamic_links' } %>_test"

production:
  primary:
    <<: *default
    database: "<%= ENV.fetch('POSTGRES_DB') { 'rails_dynamic_links' } %>_production"
  # Add additional databases here for multi-tenant support when needed
  # tenant_1:
  #   <<: *default
  #   database: "<%= ENV.fetch('POSTGRES_DB') { 'rails_dynamic_links' } %>_tenant_1_production"
