# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in dynamic_links.gemspec.
gemspec

gem 'dotenv-rails', require: 'dotenv/load'

gem 'puma'

gem 'pg', '>= 0.18', '< 2.0'

gem 'sprockets-rails'

# for dummy app
gem 'sidekiq'

group :test do
  gem 'dalli', '>= 3.2.3', require: false
  gem 'mocha'
  gem 'mock_redis'
  gem 'pry-rails'
  gem 'simplecov', require: false
  gem 'timecop'
end

gem 'nanoid', '>= 2', '< 3'
gem 'ostruct'
gem 'redis', '>= 4', '< 6'
