name: Engine Tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  test-dynamic-links:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dynamic_links_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"
          bundler-cache: true
          working-directory: ./engines/dynamic_links

      - name: Cache bundle dependencies
        uses: actions/cache@v4
        with:
          path: |
            engines/dynamic_links/vendor/bundle
            ~/.bundle
          key: ${{ runner.os }}-bundler-dynamic-links-${{ hashFiles('engines/dynamic_links/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-dynamic-links-

      - name: Install bundle dependencies
        working-directory: ./engines/dynamic_links
        run: |
          bundle config set --local deployment 'true'
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Setup database and run tests
        working-directory: ./engines/dynamic_links
        env:
          RAILS_ENV: test
          POSTGRES_DB: dynamic_links_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          RAILS_MAX_THREADS: 5
          SHORTENING_STRATEGY: md5
          REDIS_HOST: localhost
          REDIS_URL: redis://localhost:6379/0
          SECRET_KEY_BASE: test_secret_key_base_for_ci_environment
        run: |
          bundle exec rails db:drop db:create db:migrate
          bundle exec rails db:test:prepare
          bundle exec rails test

      - name: Cache test database schema
        uses: actions/cache@v4
        with:
          path: engines/dynamic_links/db/schema.rb
          key: ${{ runner.os }}-schema-dynamic-links-${{ hashFiles('engines/dynamic_links/db/migrate/**/*.rb') }}
          restore-keys: |
            ${{ runner.os }}-schema-dynamic-links-

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dynamic-links-coverage-report
          path: engines/dynamic_links/coverage/

  test-dynamic-links-analytics:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dynamic_links_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"
          bundler-cache: true

      - name: Cache bundle dependencies for analytics
        uses: actions/cache@v4
        with:
          path: |
            engines/dynamic_links_analytics/vendor/bundle
            ~/.bundle
          key: ${{ runner.os }}-bundler-analytics-${{ hashFiles('engines/dynamic_links_analytics/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-analytics-

      - name: Setup database and run analytics tests
        env:
          RAILS_ENV: test
          POSTGRES_DB: dynamic_links_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          RAILS_MAX_THREADS: 5
          SHORTENING_STRATEGY: md5
          REDIS_HOST: localhost
          REDIS_URL: redis://localhost:6379/0
          SECRET_KEY_BASE: test_secret_key_base_for_ci_environment
        run: |
          bundle exec rails db:drop db:create db:migrate
          bundle exec rails db:test:prepare
          bundle exec rails test engines/dynamic_links_analytics/test/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dynamic-links-analytics-coverage-report
          path: coverage/
