name: Publish Gem

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      gem_version:
        description: "Gem version to publish (e.g., 1.0.0)"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dynamic_links_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"
          bundler-cache: true
          working-directory: ./engines/dynamic_links

      - name: Cache bundle dependencies for gem publishing
        uses: actions/cache@v4
        with:
          path: |
            engines/dynamic_links/vendor/bundle
            ~/.bundle
          key: ${{ runner.os }}-bundler-publish-${{ hashFiles('engines/dynamic_links/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-publish-

      - name: Install bundle dependencies
        working-directory: ./engines/dynamic_links
        run: |
          bundle config set --local deployment 'true'
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Setup database and run tests
        working-directory: ./engines/dynamic_links
        env:
          RAILS_ENV: test
          POSTGRES_DB: dynamic_links_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          RAILS_MAX_THREADS: 5
          SHORTENING_STRATEGY: md5
          REDIS_HOST: localhost
          REDIS_URL: redis://localhost:6379/0
          SECRET_KEY_BASE: test_secret_key_base_for_ci_environment
        run: |
          bundle exec rails db:drop db:create db:migrate
          bundle exec rails db:test:prepare
          bundle exec rails test

      - name: Cache gem build artifacts
        uses: actions/cache@v4
        with:
          path: engines/dynamic_links/*.gem
          key: ${{ runner.os }}-gem-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Build gem
        working-directory: ./engines/dynamic_links
        run: gem build dynamic_links.gemspec

      - name: Set up authentication for GitHub Packages
        run: |
          mkdir -p $HOME/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials

      - name: Publish to GitHub Package Registry
        working-directory: ./engines/dynamic_links
        run: |
          gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
